-- Update generate_completion_otp to support all workflow states
CREATE OR REPLACE FUNCTION public.generate_completion_otp(p_booking_id UUID, p_otp_hash TEXT, p_worker_id UUID)
RETURNS JSONB AS $$
DECLARE
  v_booking public.bookings;
  v_now TIMESTAMPTZ := NOW();
BEGIN
  -- Fetch booking
  SELECT * INTO v_booking FROM public.bookings WHERE id = p_booking_id FOR UPDATE;
  
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Booking not found');
  END IF;
  
  -- Verify worker ownership
  IF v_booking.worker_id IS DISTINCT FROM p_worker_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'Forbidden: Only the assigned worker can manage completion.');
  END IF;
  
  -- Invalidate any existing OTPs for this booking
  UPDATE public.booking_completion_otps
  SET expires_at = v_now
  WHERE booking_id = p_booking_id AND verified_at IS NULL;
  
  -- Insert new OTP
  INSERT INTO public.booking_completion_otps (booking_id, otp_hash, expires_at)
  VALUES (p_booking_id, p_otp_hash, v_now + INTERVAL '10 minutes');
  
  -- Transition booking status to 'work_completed_pending_otp'
  -- Allowed from: started, work_started, work_completed, awaiting_item_approval, item_approved, awaiting_payment, payment_processing, payment_verified
  IF v_booking.status IN ('started', 'work_started', 'work_completed', 'awaiting_item_approval', 'item_approved', 'awaiting_payment', 'payment_processing', 'payment_verified') THEN
    UPDATE public.bookings
    SET status = 'work_completed_pending_otp', updated_at = v_now
    WHERE id = p_booking_id;
    
    INSERT INTO public.booking_timeline (booking_id, status, reason, created_by)
    VALUES (p_booking_id, 'work_completed_pending_otp', 'Worker requested verification. OTP generated.', p_worker_id);
  ELSE
    -- If it's already in work_completed_pending_otp, we just log the regeneration
    INSERT INTO public.booking_timeline (booking_id, status, reason, created_by)
    VALUES (p_booking_id, v_booking.status, 'Completion OTP regenerated by worker.', p_worker_id);
  END IF;
  
  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Update verify_completion_otp to handle both cash and online payment settlement
CREATE OR REPLACE FUNCTION public.verify_completion_otp(p_booking_id UUID, p_otp_hash TEXT, p_worker_id UUID)
RETURNS JSONB AS $$
DECLARE
  v_otp public.booking_completion_otps;
  v_booking public.bookings;
  v_now TIMESTAMPTZ := NOW();
  v_max_attempts INTEGER := 5;
  v_commission_res JSONB;
BEGIN
  -- Fetch booking
  SELECT * INTO v_booking FROM public.bookings WHERE id = p_booking_id FOR UPDATE;
  
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Booking not found');
  END IF;
  
  -- Verify worker ownership
  IF v_booking.worker_id IS DISTINCT FROM p_worker_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'Forbidden: Only the assigned worker can verify completion.');
  END IF;
  
  -- Fetch latest active OTP
  SELECT * INTO v_otp
  FROM public.booking_completion_otps
  WHERE booking_id = p_booking_id AND verified_at IS NULL AND expires_at > v_now
  ORDER BY created_at DESC LIMIT 1
  FOR UPDATE;
  
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'OTP has expired or is invalid. Please request a new OTP.', 'code', 400);
  END IF;
  
  -- Check attempt limit
  IF v_otp.attempts >= v_max_attempts THEN
    UPDATE public.bookings SET status = 'disputed', updated_at = v_now WHERE id = p_booking_id;
    INSERT INTO public.booking_timeline (booking_id, status, reason, created_by)
    VALUES (p_booking_id, 'disputed', 'OTP verification blocked: too many failed attempts.', p_worker_id);
    RETURN jsonb_build_object('success', false, 'error', 'Too many verification attempts. Booking marked as disputed.', 'code', 429);
  END IF;
  
  -- Verify OTP hash
  IF v_otp.otp_hash = p_otp_hash THEN
    -- Match! Update OTP record
    UPDATE public.booking_completion_otps SET verified_at = v_now WHERE id = v_otp.id;
    
    -- SETTLEMENT LOGIC
    IF v_booking.payment_method = 'cash' THEN
      -- For cash, deduct commission from worker wallet
      v_commission_res := public.process_booking_commission(p_booking_id);
    ELSE
      -- For online (upi/card), credit the worker wallet (payment was already received by platform)
      v_commission_res := public.process_online_payment_credit(p_booking_id);
    END IF;
    
    -- Finalize booking status if not already set by commission processing
    -- (Note: process_booking_commission and process_online_payment_credit already set status to 'completed')
    UPDATE public.bookings
    SET status = 'completed',
        payment_status = 'paid',
        updated_at = v_now
    WHERE id = p_booking_id;
    
    -- Clear active bookings
    DELETE FROM public.active_bookings WHERE booking_id = p_booking_id;
    
    -- Log timeline
    INSERT INTO public.booking_timeline (booking_id, status, reason, created_by)
    VALUES (p_booking_id, 'completed', 'Job completion OTP verified successfully. Settlement processed.', p_worker_id);
    
    RETURN jsonb_build_object('success', true);
  ELSE
    -- Mismatch! Increment attempts
    UPDATE public.booking_completion_otps SET attempts = attempts + 1 WHERE id = v_otp.id;
    
    IF v_otp.attempts + 1 >= v_max_attempts THEN
      UPDATE public.bookings SET status = 'disputed', updated_at = v_now WHERE id = p_booking_id;
      RETURN jsonb_build_object('success', false, 'error', 'Invalid OTP. Attempt limit exceeded. Booking marked as disputed.', 'code', 429);
    END IF;
    
    RETURN jsonb_build_object('success', false, 'error', 'Invalid OTP code. Please try again.');
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
